# Welcome to Jekyll!

# Site settings
repository: frahnklin/frahnklin.github.io
url: https://frahnklin.github.io
title: Franklin's Website
masthead_title: " "
email:
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! This is my personal website where I publish anything from
  code, tutorials, or ramblings of mine. Enjoy!
github_username: frahnklin
minimal_mistakes_skin: dirt
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
incremental: true
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Franklin R"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Bronx Science student. Pretty decent programmer."
  location : "New York, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
